/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WordCountCalendarPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// settings.ts
var DEFAULT_SETTINGS = {
  dailyGoal: 1e3,
  includeFolders: [],
  excludeFolders: [],
  dailyNotesFolder: "",
  wordCountCache: {},
  dailyNotePaths: {},
  // 默认颜色（GitHub 绿色系）
  emptyCellColor: { color: "#ebedf0", opacity: 100 },
  level1Color: { color: "#9be9a8", opacity: 100 },
  level2Color: { color: "#40c463", opacity: 100 },
  level3Color: { color: "#30a14e", opacity: 100 },
  level4Color: { color: "#216e39", opacity: 100 },
  // 默认格子大小
  cellSize: 45,
  // 默认日记模板（留空表示不使用模板）
  dailyNoteTemplate: ""
};

// word-counter.ts
var WordCounter = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  /**
   * 统计文件的词数（中英文混合）
   * 中文：按字数统计
   * 英文：按单词统计
   * @param file 要统计的文件
   * @returns 词数
   */
  async countWords(file) {
    const content = await this.app.vault.read(file);
    return this.countWordsInContent(content);
  }
  /**
   * 统计内容的词数
   * @param content 文本内容
   * @returns 词数
   */
  countWordsInContent(content) {
    content = this.removeFrontmatter(content);
    content = content.replace(/```[\s\S]*?```/g, "");
    content = content.replace(/`[^`]*`/g, "");
    content = content.replace(/\[([^\]]*)\]\([^\)]*\)/g, "$1");
    const chineseChars = content.match(/[\u4e00-\u9fa5]/g);
    const chineseCount = chineseChars ? chineseChars.length : 0;
    const nonChinese = content.replace(/[\u4e00-\u9fa5]/g, " ");
    const englishWords = nonChinese.match(/[a-zA-Z]+/g);
    const englishCount = englishWords ? englishWords.length : 0;
    return chineseCount + englishCount;
  }
  /**
   * 移除frontmatter
   */
  removeFrontmatter(content) {
    const frontmatterRegex = /^---\n[\s\S]*?\n---\n/;
    return content.replace(frontmatterRegex, "");
  }
  /**
   * 检查文件是否应该被统计（根据文件夹过滤规则）
   * @param file 要检查的文件
   * @returns 是否应该统计
   */
  shouldCountFile(file) {
    const filePath = file.path;
    if (this.settings.excludeFolders.length > 0) {
      for (const excludeFolder of this.settings.excludeFolders) {
        if (filePath.startsWith(excludeFolder)) {
          return false;
        }
      }
    }
    if (this.settings.includeFolders.length > 0) {
      for (const includeFolder of this.settings.includeFolders) {
        if (filePath.startsWith(includeFolder)) {
          return true;
        }
      }
      return false;
    }
    return true;
  }
  /**
   * 获取文件的缓存字数
   */
  getCachedWordCount(file, settings) {
    const cache = settings.wordCountCache[file.path];
    return cache || { lastCount: 0, lastUpdateDate: "" };
  }
  /**
   * 更新文件缓存
   */
  updateCache(file, wordCount, date, settings) {
    settings.wordCountCache[file.path] = {
      lastCount: wordCount,
      lastUpdateDate: date
    };
  }
};

// calendar-view.ts
var import_obsidian = require("obsidian");

// color-gradient.ts
var ColorGradient = class {
  /**
   * 将 HEX 颜色和透明度转换为 RGBA
   * @param hex HEX 颜色值，如 "#9be9a8"
   * @param opacity 透明度，范围 0-100
   * @returns RGBA 颜色值
   */
  static hexToRgba(hex, opacity) {
    hex = hex.replace("#", "");
    const r = parseInt(hex.substring(0, 2), 16);
    const g = parseInt(hex.substring(2, 4), 16);
    const b = parseInt(hex.substring(4, 6), 16);
    const alpha = opacity / 100;
    return `rgba(${r}, ${g}, ${b}, ${alpha})`;
  }
  /**
   * 根据字数和目标计算渐变色
   * @param wordCount 当前字数
   * @param goal 目标字数
   * @param colors 颜色配置对象
   * @returns 颜色值 (RGBA)
   */
  static getColor(wordCount, goal, colors) {
    if (wordCount === 0) {
      return this.hexToRgba(colors.empty.color, colors.empty.opacity);
    }
    const ratio = wordCount / goal;
    if (ratio < 0.4) {
      return this.hexToRgba(colors.level1.color, colors.level1.opacity);
    } else if (ratio < 0.7) {
      return this.hexToRgba(colors.level2.color, colors.level2.opacity);
    } else if (ratio < 1) {
      return this.hexToRgba(colors.level3.color, colors.level3.opacity);
    } else {
      return this.hexToRgba(colors.level4.color, colors.level4.opacity);
    }
  }
};

// calendar-view.ts
var VIEW_TYPE_CALENDAR = "word-count-calendar-view";
var CalendarView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.currentDate = new Date();
  }
  getViewType() {
    return VIEW_TYPE_CALENDAR;
  }
  getDisplayText() {
    return "\u5B57\u6570\u7EDF\u8BA1\u65E5\u5386";
  }
  getIcon() {
    return "calendar";
  }
  async onOpen() {
    await this.renderCalendar();
  }
  async onClose() {
  }
  /**
   * 渲染日历
   */
  async renderCalendar() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("word-count-calendar-container");
    container.style.setProperty("--calendar-cell-size", `${this.plugin.settings.cellSize}px`);
    const header = container.createDiv({ cls: "calendar-header" });
    const prevBtn = header.createEl("button", { text: "<", cls: "calendar-nav-btn" });
    prevBtn.onclick = () => this.changeMonth(-1);
    const monthDisplay = header.createDiv({ cls: "calendar-month-display" });
    monthDisplay.setText(this.getMonthYearText());
    const nextBtn = header.createEl("button", { text: ">", cls: "calendar-nav-btn" });
    nextBtn.onclick = () => this.changeMonth(1);
    const calendarGrid = container.createDiv({ cls: "calendar-grid" });
    await this.renderDays(calendarGrid);
    const footer = container.createDiv({ cls: "calendar-footer" });
    const stats = await this.calculateMonthStats();
    footer.innerHTML = `\u672C\u6708\u5DF2\u5199 <strong>${stats.totalDays}</strong> \u5929\uFF0C\u7075\u611F\u5982\u6CC9\u6D8C\uFF01<br>\u603B\u5B57\u6570\uFF1A<strong>${stats.totalWords}</strong>`;
  }
  /**
   * 渲染日历中的每一天
   */
  async renderDays(container) {
    const year = this.currentDate.getFullYear();
    const month = this.currentDate.getMonth();
    const firstDay = new Date(year, month, 1);
    const lastDay = new Date(year, month + 1, 0);
    const startWeekDay = firstDay.getDay();
    for (let i = 0; i < startWeekDay; i++) {
      container.createDiv({ cls: "calendar-day empty" });
    }
    const wordCountData = await this.getMonthWordCountData(year, month);
    for (let day = 1; day <= lastDay.getDate(); day++) {
      const dateStr = `${year}-${String(month + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
      const wordCount = wordCountData.get(dateStr) || 0;
      const dayEl = container.createDiv({ cls: "calendar-day" });
      const color = ColorGradient.getColor(
        wordCount,
        this.plugin.settings.dailyGoal,
        {
          empty: this.plugin.settings.emptyCellColor,
          level1: this.plugin.settings.level1Color,
          level2: this.plugin.settings.level2Color,
          level3: this.plugin.settings.level3Color,
          level4: this.plugin.settings.level4Color
        }
      );
      dayEl.style.backgroundColor = color;
      const dayNum = dayEl.createDiv({ cls: "calendar-day-number", text: String(day) });
      if (wordCount > 0) {
        const wordCountEl = dayEl.createDiv({ cls: "calendar-day-count", text: String(wordCount) });
        dayEl.setAttribute("title", `${dateStr}
\u7801\u5B57\uFF1A${wordCount} \u5B57`);
      } else {
        dayEl.setAttribute("title", `${dateStr}
\u65E0\u7801\u5B57\u6570\u636E`);
      }
      const today = new Date();
      if (year === today.getFullYear() && month === today.getMonth() && day === today.getDate()) {
        dayEl.addClass("today");
      }
    }
  }
  /**
   * 获取指定月份所有笔记的字数数据 - 从日记读取
   */
  async getMonthWordCountData(year, month) {
    var _a;
    const data = /* @__PURE__ */ new Map();
    const lastDay = new Date(year, month + 1, 0).getDate();
    const folder = this.plugin.settings.dailyNotesFolder || "";
    for (let day = 1; day <= lastDay; day++) {
      const dateStr = `${year}-${String(month + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
      let dailyNote = null;
      if (folder) {
        const expectedPath = `${folder}/${dateStr}.md`;
        const file = this.app.vault.getAbstractFileByPath(expectedPath);
        if (file instanceof import_obsidian.TFile) {
          dailyNote = file;
        }
      }
      if (!dailyNote && this.plugin.settings.includeFolders.length > 0) {
        for (const includeFolder of this.plugin.settings.includeFolders) {
          const expectedPath = `${includeFolder}/${dateStr}.md`;
          const file = this.app.vault.getAbstractFileByPath(expectedPath);
          if (file instanceof import_obsidian.TFile) {
            dailyNote = file;
            break;
          }
        }
      }
      if (!dailyNote) {
        const files = this.app.vault.getMarkdownFiles();
        dailyNote = files.find((f) => f.basename === dateStr) || null;
      }
      if (dailyNote) {
        const cache = this.app.metadataCache.getFileCache(dailyNote);
        const wordCount = ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a["\u7801\u5B57\u6570"]) || 0;
        data.set(dateStr, wordCount);
      }
    }
    return data;
  }
  /**
   * 计算当月统计信息
   */
  async calculateMonthStats() {
    const year = this.currentDate.getFullYear();
    const month = this.currentDate.getMonth();
    const data = await this.getMonthWordCountData(year, month);
    let totalWords = 0;
    let totalDays = 0;
    data.forEach((count) => {
      if (count > 0) {
        totalDays++;
        totalWords += count;
      }
    });
    return { totalDays, totalWords };
  }
  /**
   * 切换月份
   */
  changeMonth(delta) {
    this.currentDate.setMonth(this.currentDate.getMonth() + delta);
    this.renderCalendar();
  }
  /**
   * 获取月份年份显示文本
   */
  getMonthYearText() {
    const year = this.currentDate.getFullYear();
    const month = this.currentDate.getMonth() + 1;
    return `${year}\u5E74${month}\u6708`;
  }
  /**
   * 刷新视图
   */
  async refresh() {
    await this.renderCalendar();
  }
};

// settings-tab.ts
var import_obsidian2 = require("obsidian");
var WordCountSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  /**
   * 添加颜色和透明度设置控件
   */
  addColorWithOpacitySetting(containerEl, name, desc, colorSetting, onChange) {
    const setting = new import_obsidian2.Setting(containerEl).setName(name).setDesc(desc);
    setting.addColorPicker((colorPicker) => {
      colorPicker.setValue(colorSetting.color);
      colorPicker.onChange(async (value) => {
        colorSetting.color = value;
        await onChange(colorSetting);
      });
    });
    setting.addSlider((slider) => {
      slider.setLimits(0, 100, 1);
      slider.setValue(colorSetting.opacity);
      slider.setDynamicTooltip();
      slider.onChange(async (value) => {
        colorSetting.opacity = value;
        await onChange(colorSetting);
      });
    });
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u5B57\u6570\u7EDF\u8BA1\u65E5\u5386\u8BBE\u7F6E" });
    new import_obsidian2.Setting(containerEl).setName("\u6BCF\u65E5\u76EE\u6807\u5B57\u6570").setDesc("\u8BBE\u7F6E\u6BCF\u5929\u7684\u5199\u4F5C\u5B57\u6570\u76EE\u6807\uFF0C\u7528\u4E8E\u989C\u8272\u6E10\u53D8\u663E\u793A").addText((text) => text.setPlaceholder("1000").setValue(String(this.plugin.settings.dailyGoal)).onChange(async (value) => {
      const numValue = parseInt(value);
      if (!isNaN(numValue) && numValue > 0) {
        this.plugin.settings.dailyGoal = numValue;
        await this.plugin.saveSettings();
        this.plugin.refreshCalendarView();
      }
    }));
    containerEl.createEl("h2", { text: "\u683C\u5B50\u989C\u8272\u8BBE\u7F6E" });
    this.addColorWithOpacitySetting(
      containerEl,
      "\u65E0\u6570\u636E\u683C\u5B50\u989C\u8272",
      "\u8BBE\u7F6E\u6CA1\u6709\u6570\u636E\u7684\u65E5\u671F\u683C\u5B50\u7684\u80CC\u666F\u989C\u8272\u548C\u900F\u660E\u5EA6",
      this.plugin.settings.emptyCellColor,
      async (value) => {
        this.plugin.settings.emptyCellColor = value;
        await this.plugin.saveSettings();
        this.plugin.refreshCalendarView();
      }
    );
    this.addColorWithOpacitySetting(
      containerEl,
      "Level 1 \u989C\u8272",
      "\u5B57\u6570 < 40% \u76EE\u6807\u65F6\u7684\u683C\u5B50\u989C\u8272\u548C\u900F\u660E\u5EA6",
      this.plugin.settings.level1Color,
      async (value) => {
        this.plugin.settings.level1Color = value;
        await this.plugin.saveSettings();
        this.plugin.refreshCalendarView();
      }
    );
    this.addColorWithOpacitySetting(
      containerEl,
      "Level 2 \u989C\u8272",
      "\u5B57\u6570 40% - 70% \u76EE\u6807\u65F6\u7684\u683C\u5B50\u989C\u8272\u548C\u900F\u660E\u5EA6",
      this.plugin.settings.level2Color,
      async (value) => {
        this.plugin.settings.level2Color = value;
        await this.plugin.saveSettings();
        this.plugin.refreshCalendarView();
      }
    );
    this.addColorWithOpacitySetting(
      containerEl,
      "Level 3 \u989C\u8272",
      "\u5B57\u6570 70% - 100% \u76EE\u6807\u65F6\u7684\u683C\u5B50\u989C\u8272\u548C\u900F\u660E\u5EA6",
      this.plugin.settings.level3Color,
      async (value) => {
        this.plugin.settings.level3Color = value;
        await this.plugin.saveSettings();
        this.plugin.refreshCalendarView();
      }
    );
    this.addColorWithOpacitySetting(
      containerEl,
      "Level 4 \u989C\u8272",
      "\u5B57\u6570 \u2265 100% \u76EE\u6807\u65F6\u7684\u683C\u5B50\u989C\u8272\u548C\u900F\u660E\u5EA6",
      this.plugin.settings.level4Color,
      async (value) => {
        this.plugin.settings.level4Color = value;
        await this.plugin.saveSettings();
        this.plugin.refreshCalendarView();
      }
    );
    containerEl.createEl("h2", { text: "\u683C\u5B50\u5927\u5C0F\u8BBE\u7F6E" });
    new import_obsidian2.Setting(containerEl).setName("\u683C\u5B50\u5927\u5C0F").setDesc("\u8C03\u6574\u65E5\u5386\u683C\u5B50\u7684\u5927\u5C0F\uFF0830px - 80px\uFF09").addSlider((slider) => {
      slider.setLimits(30, 80, 1);
      slider.setValue(this.plugin.settings.cellSize);
      slider.setDynamicTooltip();
      slider.onChange(async (value) => {
        this.plugin.settings.cellSize = value;
        await this.plugin.saveSettings();
        this.plugin.refreshCalendarView();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("\u65E5\u8BB0\u6587\u4EF6\u5939").setDesc("\u65E5\u8BB0\u6587\u4EF6\u6240\u5728\u7684\u6587\u4EF6\u5939\u8DEF\u5F84\uFF08\u7559\u7A7A\u8868\u793A\u6839\u76EE\u5F55\uFF09\u3002\u4F8B\u5982\uFF1A\u65E5\u8BB0 \u6216 Daily Notes").addText((text) => text.setPlaceholder("\u7559\u7A7A\u6216\u586B\u5199\u6587\u4EF6\u5939\u8DEF\u5F84").setValue(this.plugin.settings.dailyNotesFolder).onChange(async (value) => {
      this.plugin.settings.dailyNotesFolder = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("\u65E5\u8BB0\u6A21\u677F").setDesc("\u521B\u5EFA\u65E5\u8BB0\u65F6\u4F7F\u7528\u7684\u6A21\u677F\u6587\u4EF6\u8DEF\u5F84\u3002\u6A21\u677F\u4E2D\u53EF\u4EE5\u4F7F\u7528 {{date}} \u4F5C\u4E3A\u65E5\u671F\u5360\u4F4D\u7B26\u3002\u7559\u7A7A\u5219\u4F7F\u7528\u9ED8\u8BA4\u6A21\u677F\u3002").addText((text) => text.setPlaceholder("\u7559\u7A7A\u6216\u586B\u5199\u6A21\u677F\u6587\u4EF6\u8DEF\u5F84\uFF0C\u5982\uFF1ATemplates/Daily Note.md").setValue(this.plugin.settings.dailyNoteTemplate).onChange(async (value) => {
      this.plugin.settings.dailyNoteTemplate = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("\u5305\u542B\u6587\u4EF6\u5939").setDesc("\u53EA\u7EDF\u8BA1\u8FD9\u4E9B\u6587\u4EF6\u5939\u4E2D\u7684\u6587\u4EF6\uFF08\u7559\u7A7A\u8868\u793A\u7EDF\u8BA1\u6240\u6709\u6587\u4EF6\u5939\uFF09\u3002\u591A\u4E2A\u6587\u4EF6\u5939\u8BF7\u7528\u9017\u53F7\u5206\u9694\uFF0C\u4F8B\u5982\uFF1A\u65E5\u8BB0,\u7B14\u8BB0").addTextArea((text) => {
      text.setPlaceholder("\u65E5\u8BB0,\u7B14\u8BB0").setValue(this.plugin.settings.includeFolders.join(",")).onChange(async (value) => {
        this.plugin.settings.includeFolders = value.split(",").map((f) => f.trim()).filter((f) => f.length > 0);
        await this.plugin.saveSettings();
        this.plugin.refreshCalendarView();
      });
      text.inputEl.rows = 3;
      text.inputEl.cols = 30;
    });
    new import_obsidian2.Setting(containerEl).setName("\u6392\u9664\u6587\u4EF6\u5939").setDesc("\u4E0D\u7EDF\u8BA1\u8FD9\u4E9B\u6587\u4EF6\u5939\u4E2D\u7684\u6587\u4EF6\u3002\u591A\u4E2A\u6587\u4EF6\u5939\u8BF7\u7528\u9017\u53F7\u5206\u9694").addTextArea((text) => {
      text.setPlaceholder("\u6A21\u677F,\u5F52\u6863").setValue(this.plugin.settings.excludeFolders.join(",")).onChange(async (value) => {
        this.plugin.settings.excludeFolders = value.split(",").map((f) => f.trim()).filter((f) => f.length > 0);
        await this.plugin.saveSettings();
        this.plugin.refreshCalendarView();
      });
      text.inputEl.rows = 3;
      text.inputEl.cols = 30;
    });
    new import_obsidian2.Setting(containerEl).setName("\u6E05\u7A7A\u5B57\u6570\u7F13\u5B58").setDesc("\u6E05\u7A7A\u6240\u6709\u6587\u4EF6\u7684\u5B57\u6570\u7F13\u5B58\u3002\u4E0B\u6B21\u7F16\u8F91\u6587\u4EF6\u65F6\u4F1A\u91CD\u65B0\u5EFA\u7ACB\u57FA\u7EBF\u3002\u5982\u679C\u9047\u5230\u5B57\u6570\u7EDF\u8BA1\u91CD\u590D\u6216\u4E0D\u51C6\u786E\u7684\u95EE\u9898\uFF0C\u53EF\u4EE5\u5C1D\u8BD5\u6E05\u7A7A\u7F13\u5B58\u3002").addButton((button) => button.setButtonText("\u6E05\u7A7A\u7F13\u5B58").setWarning().onClick(async () => {
      const confirmed = confirm(
        "\u786E\u5B9A\u8981\u6E05\u7A7A\u6240\u6709\u5B57\u6570\u7F13\u5B58\u5417\uFF1F\n\n\u6E05\u7A7A\u540E\uFF0C\u6240\u6709\u6587\u4EF6\u5728\u4E0B\u6B21\u7F16\u8F91\u65F6\u4F1A\u91CD\u65B0\u5EFA\u7ACB\u5B57\u6570\u57FA\u7EBF\u3002\n\u8FD9\u4E0D\u4F1A\u5F71\u54CD\u5DF2\u8BB0\u5F55\u7684\u65E5\u8BB0\u6570\u636E\u3002"
      );
      if (confirmed) {
        this.plugin.settings.wordCountCache = {};
        await this.plugin.saveSettings();
        button.setButtonText("\u5DF2\u6E05\u7A7A");
        setTimeout(() => {
          button.setButtonText("\u6E05\u7A7A\u7F13\u5B58");
        }, 2e3);
      }
    }));
    containerEl.createEl("h3", { text: "\u989C\u8272\u8BF4\u660E" });
    const colorDesc = containerEl.createDiv({ cls: "word-count-color-description" });
    colorDesc.createEl("p", { text: "\u65E5\u5386\u989C\u8272\u53C2\u8003 GitHub \u8D21\u732E\u56FE\u6A21\u5F0F (\u7EFF\u8272\u7CFB)\uFF1A" });
    const ul = colorDesc.createEl("ul");
    ul.createEl("li", { text: "\u989C\u8272\u968F\u5B57\u6570\u589E\u52A0\u800C\u53D8\u6DF1 (\u51714\u4E2A\u7B49\u7EA7)" });
    ul.createEl("li", { text: "Level 1: < 40% \u76EE\u6807" });
    ul.createEl("li", { text: "Level 2: 40% - 70% \u76EE\u6807" });
    ul.createEl("li", { text: "Level 3: 70% - 100% \u76EE\u6807" });
    ul.createEl("li", { text: "Level 4: \u2265 100% \u76EE\u6807" });
    ul.createEl("li", { text: "\u65E0\u6570\u636E\uFF1A\u53EF\u81EA\u5B9A\u4E49\u989C\u8272" });
    containerEl.createEl("h3", { text: "\u4F7F\u7528\u8BF4\u660E" });
    const usageDesc = containerEl.createDiv({ cls: "word-count-color-description" });
    usageDesc.createEl("p", { text: "\u63D2\u4EF6\u4F7F\u7528\u589E\u91CF\u7EDF\u8BA1\u65B9\u5F0F\uFF1A" });
    const usageUl = usageDesc.createEl("ul");
    usageUl.createEl("li", { text: "\u7F16\u8F91\u6587\u4EF6\u65F6\uFF0C\u53EA\u7EDF\u8BA1\u65B0\u589E\u7684\u5B57\u6570" });
    usageUl.createEl("li", { text: "\u5B57\u6570\u81EA\u52A8\u8BB0\u5F55\u5230\u5F53\u5929\u7684\u65E5\u8BB0\u6587\u4EF6\uFF08YYYY-MM-DD.md\u683C\u5F0F\uFF09" });
    usageUl.createEl("li", { text: "\u5982\u679C\u65E5\u8BB0\u4E0D\u5B58\u5728\uFF0C\u4F1A\u81EA\u52A8\u521B\u5EFA" });
    usageUl.createEl("li", { text: "\u53F3\u4E0B\u89D2\u72B6\u6001\u680F\u5B9E\u65F6\u663E\u793A\u4ECA\u65E5\u7801\u5B57\u6570" });
  }
};

// main.ts
var WordCountCalendarPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.todayWordCount = 0;
    /**
     * WPM计算器
     */
    this.wpmCalculator = new WPMCalculator();
    this.wpmTimer = null;
    this.settingsSaveTimer = null;
  }
  async onload() {
    console.log("\u52A0\u8F7D\u5B57\u6570\u7EDF\u8BA1\u65E5\u5386\u63D2\u4EF6");
    await this.loadSettings();
    this.wordCounter = new WordCounter(this.app, this.settings);
    this.registerView(
      VIEW_TYPE_CALENDAR,
      (leaf) => new CalendarView(leaf, this)
    );
    this.addRibbonIcon("calendar", "\u5B57\u6570\u7EDF\u8BA1\u65E5\u5386", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-word-count-calendar",
      name: "\u6253\u5F00\u5B57\u6570\u7EDF\u8BA1\u65E5\u5386",
      callback: () => {
        this.activateView();
      }
    });
    this.registerEvent(
      this.app.vault.on("modify", async (file) => {
        if (file instanceof import_obsidian3.TFile && file.extension === "md") {
          await this.onFileModified(file);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("create", async (file) => {
        if (file instanceof import_obsidian3.TFile && file.extension === "md") {
          await this.onFileCreated(file);
        }
      })
    );
    this.registerEvent(
      this.app.metadataCache.on("changed", (file) => {
        const today = this.getDateString(new Date());
        if (file instanceof import_obsidian3.TFile && file.basename === today) {
          this.updateTodayWordCount();
          this.refreshCalendarView();
        }
      })
    );
    this.addSettingTab(new WordCountSettingTab(this.app, this));
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.setText("\u4ECA\u65E5\u7801\u5B57: \u52A0\u8F7D\u4E2D...");
    setTimeout(() => {
      this.updateTodayWordCount();
    }, 1e3);
    this.registerInterval(
      window.setInterval(() => {
        const wpm = this.wpmCalculator.getWPM();
        if (wpm > 0 || this.statusBarItem.getText().includes("\u{1F680}")) {
          this.updateStatusBar();
        }
      }, 2e3)
    );
  }
  onunload() {
    console.log("\u5378\u8F7D\u5B57\u6570\u7EDF\u8BA1\u65E5\u5386\u63D2\u4EF6");
  }
  /**
   * 获取日期字符串 YYYY-MM-DD
   */
  getDateString(date) {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");
    return `${year}-${month}-${day}`;
  }
  /**
   * 查找日记文件
   */
  async findDailyNote(dateStr) {
    if (this.settings.dailyNotePaths[dateStr]) {
      const cachedFile = this.app.vault.getAbstractFileByPath(this.settings.dailyNotePaths[dateStr]);
      if (cachedFile instanceof import_obsidian3.TFile) {
        return cachedFile;
      }
      delete this.settings.dailyNotePaths[dateStr];
    }
    const folder = this.settings.dailyNotesFolder || "";
    if (folder) {
      const expectedPath = `${folder}/${dateStr}.md`;
      const directFile = this.app.vault.getAbstractFileByPath(expectedPath);
      if (directFile instanceof import_obsidian3.TFile) {
        this.settings.dailyNotePaths[dateStr] = directFile.path;
        await this.saveSettings();
        return directFile;
      }
    }
    if (this.settings.includeFolders.length > 0) {
      for (const includeFolder of this.settings.includeFolders) {
        const expectedPath = `${includeFolder}/${dateStr}.md`;
        const directFile = this.app.vault.getAbstractFileByPath(expectedPath);
        if (directFile instanceof import_obsidian3.TFile) {
          this.settings.dailyNotePaths[dateStr] = directFile.path;
          await this.saveSettings();
          return directFile;
        }
      }
    }
    const files = this.app.vault.getMarkdownFiles();
    const found = files.find((f) => f.basename === dateStr);
    if (found) {
      this.settings.dailyNotePaths[dateStr] = found.path;
      await this.saveSettings();
    }
    return found || null;
  }
  /**
   * 创建日记文件
   */
  async createDailyNote(dateStr) {
    const folder = this.settings.dailyNotesFolder || "";
    if (folder) {
      const folderExists = this.app.vault.getAbstractFileByPath(folder);
      if (!folderExists) {
        try {
          await this.app.vault.createFolder(folder);
        } catch (e) {
          console.error("\u521B\u5EFA\u6587\u4EF6\u5939\u5931\u8D25:", e);
        }
      }
    }
    const path = folder ? `${folder}/${dateStr}.md` : `${dateStr}.md`;
    try {
      let content = "";
      if (this.settings.dailyNoteTemplate) {
        const templateFile = this.app.vault.getAbstractFileByPath(this.settings.dailyNoteTemplate);
        if (templateFile instanceof import_obsidian3.TFile) {
          content = await this.app.vault.read(templateFile);
          content = content.replace(/\{\{date\}\}/g, dateStr);
        } else {
          console.warn(`\u6A21\u677F\u6587\u4EF6\u4E0D\u5B58\u5728: ${this.settings.dailyNoteTemplate}\uFF0C\u4F7F\u7528\u9ED8\u8BA4\u6A21\u677F`);
          content = `---
\u7801\u5B57\u6570: 0
---
# ${dateStr}

`;
        }
      } else {
        content = `---
\u7801\u5B57\u6570: 0
---
# ${dateStr}

`;
      }
      const file = await this.app.vault.create(path, content);
      return file;
    } catch (e) {
      console.error("\u521B\u5EFA\u65E5\u8BB0\u5931\u8D25:", e);
      new import_obsidian3.Notice(`\u521B\u5EFA\u65E5\u8BB0\u5931\u8D25: ${e.message}`);
      return null;
    }
  }
  /**
   * 获取或创建日记
   */
  async getOrCreateDailyNote(dateStr) {
    let dailyNote = await this.findDailyNote(dateStr);
    if (!dailyNote) {
      dailyNote = await this.createDailyNote(dateStr);
    }
    return dailyNote;
  }
  /**
   * 向日记增加字数
   */
  async addWordCountToDailyNote(dateStr, increment) {
    const dailyNote = await this.getOrCreateDailyNote(dateStr);
    if (!dailyNote) {
      console.log(`\u65E0\u6CD5\u521B\u5EFA\u65E5\u8BB0: ${dateStr}`);
      return;
    }
    await this.app.fileManager.processFrontMatter(dailyNote, (frontmatter) => {
      const current = frontmatter["\u7801\u5B57\u6570"] || 0;
      frontmatter["\u7801\u5B57\u6570"] = current + increment;
    });
  }
  /**
   * 更新状态栏显示
   */
  updateStatusBar() {
    if (!this.statusBarItem)
      return;
    const wpm = this.wpmCalculator.getWPM();
    let text = `\u4ECA\u65E5\u7801\u5B57: ${this.todayWordCount}`;
    if (wpm > 0) {
      text += ` | \u{1F680} ${wpm} \u5B57/\u5206`;
    }
    this.statusBarItem.setText(text);
  }
  /**
   * 更新今日字数显示（同时更新状态栏）
   */
  async updateTodayWordCount() {
    var _a;
    const today = this.getDateString(new Date());
    const dailyNote = await this.findDailyNote(today);
    if (dailyNote) {
      const cache = this.app.metadataCache.getFileCache(dailyNote);
      this.todayWordCount = ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a["\u7801\u5B57\u6570"]) || 0;
    } else {
      this.todayWordCount = 0;
    }
    this.updateStatusBar();
  }
  /**
   * 激活日历视图
   */
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_CALENDAR)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        await rightLeaf.setViewState({
          type: VIEW_TYPE_CALENDAR,
          active: true
        });
        leaf = rightLeaf;
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  /**
   * 文件修改时的处理 - 增量统计
   */
  async onFileModified(file) {
    if (!this.wordCounter.shouldCountFile(file)) {
      return;
    }
    const today = this.getDateString(new Date());
    const currentCount = await this.wordCounter.countWords(file);
    const cache = this.wordCounter.getCachedWordCount(file, this.settings);
    if (cache.lastCount === 0) {
      this.wordCounter.updateCache(file, currentCount, today, this.settings);
      await this.saveSettings();
      return;
    }
    let increment = currentCount - cache.lastCount;
    if (increment > 0) {
      this.wpmCalculator.add(increment);
      this.updateStatusBar();
    }
    if (increment < -100) {
      increment = 0;
    }
    this.wordCounter.updateCache(file, currentCount, today, this.settings);
    await this.saveSettings();
    if (increment !== 0) {
      await this.addWordCountToDailyNote(today, increment);
      await this.updateTodayWordCount();
    }
    this.refreshCalendarView();
  }
  /**
   * 文件创建时的处理
   */
  async onFileCreated(file) {
    if (!this.wordCounter.shouldCountFile(file)) {
      return;
    }
    const today = this.getDateString(new Date());
    this.wordCounter.updateCache(file, 0, today, this.settings);
    await this.saveSettings();
  }
  /**
   * 刷新日历视图
   */
  refreshCalendarView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_CALENDAR);
    leaves.forEach((leaf) => {
      if (leaf.view instanceof CalendarView) {
        leaf.view.refresh();
      }
    });
  }
  /**
   * 加载设置
   */
  async loadSettings() {
    const loadedSettings = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loadedSettings);
    this.migrateSettings();
    this.cleanOldCache();
  }
  /**
   * 数据迁移：确保旧版本设置能够正常工作
   */
  migrateSettings() {
    if (typeof this.settings.emptyCellColor === "string") {
      const oldColor = this.settings.emptyCellColor;
      this.settings.emptyCellColor = { color: oldColor, opacity: 100 };
    }
    if (!this.settings.level1Color) {
      this.settings.level1Color = DEFAULT_SETTINGS.level1Color;
    }
    if (!this.settings.level2Color) {
      this.settings.level2Color = DEFAULT_SETTINGS.level2Color;
    }
    if (!this.settings.level3Color) {
      this.settings.level3Color = DEFAULT_SETTINGS.level3Color;
    }
    if (!this.settings.level4Color) {
      this.settings.level4Color = DEFAULT_SETTINGS.level4Color;
    }
    if (typeof this.settings.cellSize === "undefined") {
      this.settings.cellSize = DEFAULT_SETTINGS.cellSize;
    }
    if (typeof this.settings.dailyNoteTemplate === "undefined") {
      this.settings.dailyNoteTemplate = DEFAULT_SETTINGS.dailyNoteTemplate;
    }
  }
  /**
   * 清理过期缓存数据
   */
  cleanOldCache() {
    const sevenDaysAgo = new Date();
    sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);
    const sevenDaysAgoStr = this.getDateString(sevenDaysAgo);
    let cleanedCount = 0;
    for (const filePath in this.settings.wordCountCache) {
      const cache = this.settings.wordCountCache[filePath];
      if (cache.lastUpdateDate < sevenDaysAgoStr || cache.lastCount === 0) {
        delete this.settings.wordCountCache[filePath];
        cleanedCount++;
      }
    }
    for (const dateStr in this.settings.dailyNotePaths) {
      if (dateStr < sevenDaysAgoStr) {
        delete this.settings.dailyNotePaths[dateStr];
      }
    }
    if (cleanedCount > 0) {
      console.log(`\u6E05\u7406\u4E86 ${cleanedCount} \u4E2A\u8FC7\u671F\u7F13\u5B58\u6761\u76EE`);
      this.saveSettings();
    }
  }
  /**
   * 保存设置（延迟保存，避免频繁写入）
   */
  async saveSettings() {
    if (this.settingsSaveTimer !== null) {
      window.clearTimeout(this.settingsSaveTimer);
    }
    this.settingsSaveTimer = window.setTimeout(async () => {
      await this.saveData(this.settings);
      this.settingsSaveTimer = null;
    }, 1e3);
  }
};
var WPMCalculator = class {
  constructor() {
    this.history = [];
    this.WINDOW_MS = 60 * 1e3;
  }
  // 60秒窗口
  /**
   * 添加输入记录
   */
  add(count) {
    if (count <= 0)
      return;
    this.history.push({ time: Date.now(), count });
  }
  /**
   * 获取当前 WPM
   */
  getWPM() {
    const now = Date.now();
    this.history = this.history.filter((item) => now - item.time < this.WINDOW_MS);
    return this.history.reduce((sum, item) => sum + item.count, 0);
  }
};
